//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VESCServices.BL.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VescMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VescMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VESCServices.BL.Resource.VescMessages", typeof(VescMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo obligatorio.
        /// </summary>
        internal static string CampoObligatorio {
            get {
                return ResourceManager.GetString("CampoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se permite el uso de constructores vacios, error al implementar la capa de seguridad!.
        /// </summary>
        internal static string ConstructorVacio {
            get {
                return ResourceManager.GetString("ConstructorVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo sentimos, algo salio mal. Proporciona este codigo de error al administrador del sistema: código de error: .
        /// </summary>
        internal static string ErrorDesconocido {
            get {
                return ResourceManager.GetString("ErrorDesconocido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo sentidmos, salio mal. Ip no valida!.
        /// </summary>
        internal static string IpVacia {
            get {
                return ResourceManager.GetString("IpVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo sentimos, algo salio mal. Request no valido!.
        /// </summary>
        internal static string requestNull {
            get {
                return ResourceManager.GetString("requestNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ya cuenta con sesiones activas, ¿Deseas cerrar iniciar sesión en este equipo?.
        /// </summary>
        internal static string SesionActiva {
            get {
                return ResourceManager.GetString("SesionActiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, inicia sesión!.
        /// </summary>
        internal static string SesionNoValida {
            get {
                return ResourceManager.GetString("SesionNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario y/o contraseña son incorrectas!.
        /// </summary>
        internal static string UsarioContrasenaNoValida {
            get {
                return ResourceManager.GetString("UsarioContrasenaNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario y/o constraseña no pueden ser vacias!.
        /// </summary>
        internal static string UsuarioContrasenaVacia {
            get {
                return ResourceManager.GetString("UsuarioContrasenaVacia", resourceCulture);
            }
        }
    }
}
