//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VESC.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBaseDTO", Namespace="http://schemas.datacontract.org/2004/07/VESCServices.ENT.Common")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VESC.ServiceReference.GetRazonSocialRequestDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VESC.ServiceReference.LogoutRequestDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VESC.ServiceReference.SendPasswordRequestDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VESC.ServiceReference.ChangePasswordRequestDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VESC.ServiceReference.AltaEmpleadoRequestDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VESC.ServiceReference.EditEmpleadoRequestDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VESC.ServiceReference.BuscarEmpleadoRequestDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VESC.ServiceReference.ConsultaPadronRequestDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VESC.ServiceReference.LoginRequestDTO))]
    public partial class RequestBaseDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid tokenSesionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ip {
            get {
                return this.ipField;
            }
            set {
                if ((object.ReferenceEquals(this.ipField, value) != true)) {
                    this.ipField = value;
                    this.RaisePropertyChanged("ip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid tokenSesion {
            get {
                return this.tokenSesionField;
            }
            set {
                if ((this.tokenSesionField.Equals(value) != true)) {
                    this.tokenSesionField = value;
                    this.RaisePropertyChanged("tokenSesion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRazonSocialRequestDTO", Namespace="http://schemas.datacontract.org/2004/07/VESCServices.ENT.Request.RazonSocial")]
    [System.SerializableAttribute()]
    public partial class GetRazonSocialRequestDTO : VESC.ServiceReference.RequestBaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRazonSocial {
            get {
                return this.IdRazonSocialField;
            }
            set {
                if ((this.IdRazonSocialField.Equals(value) != true)) {
                    this.IdRazonSocialField = value;
                    this.RaisePropertyChanged("IdRazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogoutRequestDTO", Namespace="http://schemas.datacontract.org/2004/07/VESCServices.ENT.Request.Account")]
    [System.SerializableAttribute()]
    public partial class LogoutRequestDTO : VESC.ServiceReference.RequestBaseDTO {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendPasswordRequestDTO", Namespace="http://schemas.datacontract.org/2004/07/VESCServices.ENT.Request.Account")]
    [System.SerializableAttribute()]
    public partial class SendPasswordRequestDTO : VESC.ServiceReference.RequestBaseDTO {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangePasswordRequestDTO", Namespace="http://schemas.datacontract.org/2004/07/VESCServices.ENT.Request.Account")]
    [System.SerializableAttribute()]
    public partial class ChangePasswordRequestDTO : VESC.ServiceReference.RequestBaseDTO {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AltaEmpleadoRequestDTO", Namespace="http://schemas.datacontract.org/2004/07/VESCServices.ENT.Request.Empleado")]
    [System.SerializableAttribute()]
    public partial class AltaEmpleadoRequestDTO : VESC.ServiceReference.RequestBaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VESC.ServiceReference.EmpleadoDTO[] ListaEmpleadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VESC.ServiceReference.EmpleadoDTO[] ListaEmpleado {
            get {
                return this.ListaEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaEmpleadoField, value) != true)) {
                    this.ListaEmpleadoField = value;
                    this.RaisePropertyChanged("ListaEmpleado");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EditEmpleadoRequestDTO", Namespace="http://schemas.datacontract.org/2004/07/VESCServices.ENT.Request.Empleado")]
    [System.SerializableAttribute()]
    public partial class EditEmpleadoRequestDTO : VESC.ServiceReference.RequestBaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VESC.ServiceReference.EmpleadoDTO[] ListaEmpleadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VESC.ServiceReference.EmpleadoDTO[] ListaEmpleado {
            get {
                return this.ListaEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaEmpleadoField, value) != true)) {
                    this.ListaEmpleadoField = value;
                    this.RaisePropertyChanged("ListaEmpleado");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BuscarEmpleadoRequestDTO", Namespace="http://schemas.datacontract.org/2004/07/VESCServices.ENT.Request.Empleado")]
    [System.SerializableAttribute()]
    public partial class BuscarEmpleadoRequestDTO : VESC.ServiceReference.RequestBaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VESC.ServiceReference.FiltroBusquedaEmpleadoDTO FiltroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VESC.ServiceReference.FiltroBusquedaEmpleadoDTO Filtro {
            get {
                return this.FiltroField;
            }
            set {
                if ((object.ReferenceEquals(this.FiltroField, value) != true)) {
                    this.FiltroField = value;
                    this.RaisePropertyChanged("Filtro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaPadronRequestDTO", Namespace="http://schemas.datacontract.org/2004/07/VESCServices.ENT.Request.Padron")]
    [System.SerializableAttribute()]
    public partial class ConsultaPadronRequestDTO : VESC.ServiceReference.RequestBaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpresaIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpresaId {
            get {
                return this.EmpresaIdField;
            }
            set {
                if ((this.EmpresaIdField.Equals(value) != true)) {
                    this.EmpresaIdField = value;
                    this.RaisePropertyChanged("EmpresaId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginRequestDTO", Namespace="http://schemas.datacontract.org/2004/07/VESCServices.ENT.Request.Account")]
    [System.SerializableAttribute()]
    public partial class LoginRequestDTO : VESC.ServiceReference.RequestBaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.contrasenaField, value) != true)) {
                    this.contrasenaField = value;
                    this.RaisePropertyChanged("contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpleadoDTO", Namespace="http://schemas.datacontract.org/2004/07/VESCServices.ENT.Entities")]
    [System.SerializableAttribute()]
    public partial class EmpleadoDTO : VESC.ServiceReference.ResponseBaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string calleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string coloniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string curpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cusIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool estatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaInsertField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> fechaUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string generoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idClubField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> idEmpleadoPadreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idEmpresaInfFiscalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPlanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idTipoPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string municipioDelegacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numExteriorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> numInteriorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string razonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rfcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefono2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioInsertField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioUpdateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidoM {
            get {
                return this.apellidoMField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoMField, value) != true)) {
                    this.apellidoMField = value;
                    this.RaisePropertyChanged("apellidoM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidoP {
            get {
                return this.apellidoPField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoPField, value) != true)) {
                    this.apellidoPField = value;
                    this.RaisePropertyChanged("apellidoP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string calle {
            get {
                return this.calleField;
            }
            set {
                if ((object.ReferenceEquals(this.calleField, value) != true)) {
                    this.calleField = value;
                    this.RaisePropertyChanged("calle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string colonia {
            get {
                return this.coloniaField;
            }
            set {
                if ((object.ReferenceEquals(this.coloniaField, value) != true)) {
                    this.coloniaField = value;
                    this.RaisePropertyChanged("colonia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cp {
            get {
                return this.cpField;
            }
            set {
                if ((this.cpField.Equals(value) != true)) {
                    this.cpField = value;
                    this.RaisePropertyChanged("cp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string curp {
            get {
                return this.curpField;
            }
            set {
                if ((object.ReferenceEquals(this.curpField, value) != true)) {
                    this.curpField = value;
                    this.RaisePropertyChanged("curp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cusId {
            get {
                return this.cusIdField;
            }
            set {
                if ((object.ReferenceEquals(this.cusIdField, value) != true)) {
                    this.cusIdField = value;
                    this.RaisePropertyChanged("cusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string empresa {
            get {
                return this.empresaField;
            }
            set {
                if ((object.ReferenceEquals(this.empresaField, value) != true)) {
                    this.empresaField = value;
                    this.RaisePropertyChanged("empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool estatus {
            get {
                return this.estatusField;
            }
            set {
                if ((this.estatusField.Equals(value) != true)) {
                    this.estatusField = value;
                    this.RaisePropertyChanged("estatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaInsert {
            get {
                return this.fechaInsertField;
            }
            set {
                if ((this.fechaInsertField.Equals(value) != true)) {
                    this.fechaInsertField = value;
                    this.RaisePropertyChanged("fechaInsert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                if ((this.fechaNacimientoField.Equals(value) != true)) {
                    this.fechaNacimientoField = value;
                    this.RaisePropertyChanged("fechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechaUpdate {
            get {
                return this.fechaUpdateField;
            }
            set {
                if ((this.fechaUpdateField.Equals(value) != true)) {
                    this.fechaUpdateField = value;
                    this.RaisePropertyChanged("fechaUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string genero {
            get {
                return this.generoField;
            }
            set {
                if ((object.ReferenceEquals(this.generoField, value) != true)) {
                    this.generoField = value;
                    this.RaisePropertyChanged("genero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idClub {
            get {
                return this.idClubField;
            }
            set {
                if ((this.idClubField.Equals(value) != true)) {
                    this.idClubField = value;
                    this.RaisePropertyChanged("idClub");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long idEmpleado {
            get {
                return this.idEmpleadoField;
            }
            set {
                if ((this.idEmpleadoField.Equals(value) != true)) {
                    this.idEmpleadoField = value;
                    this.RaisePropertyChanged("idEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> idEmpleadoPadre {
            get {
                return this.idEmpleadoPadreField;
            }
            set {
                if ((this.idEmpleadoPadreField.Equals(value) != true)) {
                    this.idEmpleadoPadreField = value;
                    this.RaisePropertyChanged("idEmpleadoPadre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEmpresa {
            get {
                return this.idEmpresaField;
            }
            set {
                if ((this.idEmpresaField.Equals(value) != true)) {
                    this.idEmpresaField = value;
                    this.RaisePropertyChanged("idEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEmpresaInfFiscal {
            get {
                return this.idEmpresaInfFiscalField;
            }
            set {
                if ((this.idEmpresaInfFiscalField.Equals(value) != true)) {
                    this.idEmpresaInfFiscalField = value;
                    this.RaisePropertyChanged("idEmpresaInfFiscal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPlan {
            get {
                return this.idPlanField;
            }
            set {
                if ((this.idPlanField.Equals(value) != true)) {
                    this.idPlanField = value;
                    this.RaisePropertyChanged("idPlan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTipoPago {
            get {
                return this.idTipoPagoField;
            }
            set {
                if ((this.idTipoPagoField.Equals(value) != true)) {
                    this.idTipoPagoField = value;
                    this.RaisePropertyChanged("idTipoPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string municipioDelegacion {
            get {
                return this.municipioDelegacionField;
            }
            set {
                if ((object.ReferenceEquals(this.municipioDelegacionField, value) != true)) {
                    this.municipioDelegacionField = value;
                    this.RaisePropertyChanged("municipioDelegacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numEmpleado {
            get {
                return this.numEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.numEmpleadoField, value) != true)) {
                    this.numEmpleadoField = value;
                    this.RaisePropertyChanged("numEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numExterior {
            get {
                return this.numExteriorField;
            }
            set {
                if ((this.numExteriorField.Equals(value) != true)) {
                    this.numExteriorField = value;
                    this.RaisePropertyChanged("numExterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> numInterior {
            get {
                return this.numInteriorField;
            }
            set {
                if ((this.numInteriorField.Equals(value) != true)) {
                    this.numInteriorField = value;
                    this.RaisePropertyChanged("numInterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string razonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.razonSocialField, value) != true)) {
                    this.razonSocialField = value;
                    this.RaisePropertyChanged("razonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rfc {
            get {
                return this.rfcField;
            }
            set {
                if ((object.ReferenceEquals(this.rfcField, value) != true)) {
                    this.rfcField = value;
                    this.RaisePropertyChanged("rfc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono2 {
            get {
                return this.telefono2Field;
            }
            set {
                if ((object.ReferenceEquals(this.telefono2Field, value) != true)) {
                    this.telefono2Field = value;
                    this.RaisePropertyChanged("telefono2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuarioInsert {
            get {
                return this.usuarioInsertField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioInsertField, value) != true)) {
                    this.usuarioInsertField = value;
                    this.RaisePropertyChanged("usuarioInsert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuarioUpdate {
            get {
                return this.usuarioUpdateField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioUpdateField, value) != true)) {
                    this.usuarioUpdateField = value;
                    this.RaisePropertyChanged("usuarioUpdate");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBaseDTO", Namespace="http://schemas.datacontract.org/2004/07/VESCServices.ENT.Common")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VESC.ServiceReference.AltaEmpleadoResponseDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VESC.ServiceReference.EditEmpleadoResponseDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VESC.ServiceReference.BuscarEmpleadoResponseDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VESC.ServiceReference.ConsultaPadronResponseDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VESC.ServiceReference.LoginResponseDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VESC.ServiceReference.SendPasswordResponseDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VESC.ServiceReference.ChangePasswordResponseDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VESC.ServiceReference.EmpleadoDTO))]
    public partial class ResponseBaseDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VESC.ServiceReference.ErrorDTO[] ErrorListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VESC.ServiceReference.ErrorDTO[] ErrorList {
            get {
                return this.ErrorListField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorListField, value) != true)) {
                    this.ErrorListField = value;
                    this.RaisePropertyChanged("ErrorList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AltaEmpleadoResponseDTO", Namespace="http://schemas.datacontract.org/2004/07/VESCServices.ENT.Response.Empleado")]
    [System.SerializableAttribute()]
    public partial class AltaEmpleadoResponseDTO : VESC.ServiceReference.ResponseBaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VESC.ServiceReference.EmpleadoDTO[] ListaEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VESC.ServiceReference.EmpleadoDTO[] ListaEmpleado {
            get {
                return this.ListaEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaEmpleadoField, value) != true)) {
                    this.ListaEmpleadoField = value;
                    this.RaisePropertyChanged("ListaEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EditEmpleadoResponseDTO", Namespace="http://schemas.datacontract.org/2004/07/VESCServices.ENT.Response.Empleado")]
    [System.SerializableAttribute()]
    public partial class EditEmpleadoResponseDTO : VESC.ServiceReference.ResponseBaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VESC.ServiceReference.EmpleadoDTO[] ListaEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VESC.ServiceReference.EmpleadoDTO[] ListaEmpleado {
            get {
                return this.ListaEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaEmpleadoField, value) != true)) {
                    this.ListaEmpleadoField = value;
                    this.RaisePropertyChanged("ListaEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BuscarEmpleadoResponseDTO", Namespace="http://schemas.datacontract.org/2004/07/VESCServices.ENT.Response.Empleado")]
    [System.SerializableAttribute()]
    public partial class BuscarEmpleadoResponseDTO : VESC.ServiceReference.ResponseBaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VESC.ServiceReference.EmpleadoDTO[] ListaEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VESC.ServiceReference.EmpleadoDTO[] ListaEmpleado {
            get {
                return this.ListaEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaEmpleadoField, value) != true)) {
                    this.ListaEmpleadoField = value;
                    this.RaisePropertyChanged("ListaEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaPadronResponseDTO", Namespace="http://schemas.datacontract.org/2004/07/VESCServices.ENT.Response.Padron")]
    [System.SerializableAttribute()]
    public partial class ConsultaPadronResponseDTO : VESC.ServiceReference.ResponseBaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VESC.ServiceReference.PadronDTO[] PadronListaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VESC.ServiceReference.PadronDTO[] PadronLista {
            get {
                return this.PadronListaField;
            }
            set {
                if ((object.ReferenceEquals(this.PadronListaField, value) != true)) {
                    this.PadronListaField = value;
                    this.RaisePropertyChanged("PadronLista");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResponseDTO", Namespace="http://schemas.datacontract.org/2004/07/VESCServices.ENT.Response.Account")]
    [System.SerializableAttribute()]
    public partial class LoginResponseDTO : VESC.ServiceReference.ResponseBaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid TokenSesionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TokenSesion {
            get {
                return this.TokenSesionField;
            }
            set {
                if ((this.TokenSesionField.Equals(value) != true)) {
                    this.TokenSesionField = value;
                    this.RaisePropertyChanged("TokenSesion");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendPasswordResponseDTO", Namespace="http://schemas.datacontract.org/2004/07/VESCServices.ENT.Response.Account")]
    [System.SerializableAttribute()]
    public partial class SendPasswordResponseDTO : VESC.ServiceReference.ResponseBaseDTO {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangePasswordResponseDTO", Namespace="http://schemas.datacontract.org/2004/07/VESCServices.ENT.Response.Account")]
    [System.SerializableAttribute()]
    public partial class ChangePasswordResponseDTO : VESC.ServiceReference.ResponseBaseDTO {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorDTO", Namespace="http://schemas.datacontract.org/2004/07/VESCServices.ENT.Common")]
    [System.SerializableAttribute()]
    public partial class ErrorDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripctionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripction {
            get {
                return this.DescripctionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripctionField, value) != true)) {
                    this.DescripctionField = value;
                    this.RaisePropertyChanged("Descripction");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PadronDTO", Namespace="http://schemas.datacontract.org/2004/07/VESCServices.ENT.Entities")]
    [System.SerializableAttribute()]
    public partial class PadronDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClubField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ESIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ETField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpleadoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstatusDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ICField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ICSIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal IEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal IRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ITCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RSIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string planField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Club {
            get {
                return this.ClubField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubField, value) != true)) {
                    this.ClubField = value;
                    this.RaisePropertyChanged("Club");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ESI {
            get {
                return this.ESIField;
            }
            set {
                if ((this.ESIField.Equals(value) != true)) {
                    this.ESIField = value;
                    this.RaisePropertyChanged("ESI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ET {
            get {
                return this.ETField;
            }
            set {
                if ((this.ETField.Equals(value) != true)) {
                    this.ETField = value;
                    this.RaisePropertyChanged("ET");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Empleado {
            get {
                return this.EmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoField, value) != true)) {
                    this.EmpleadoField = value;
                    this.RaisePropertyChanged("Empleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpleadoId {
            get {
                return this.EmpleadoIdField;
            }
            set {
                if ((this.EmpleadoIdField.Equals(value) != true)) {
                    this.EmpleadoIdField = value;
                    this.RaisePropertyChanged("EmpleadoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estatus {
            get {
                return this.EstatusField;
            }
            set {
                if ((this.EstatusField.Equals(value) != true)) {
                    this.EstatusField = value;
                    this.RaisePropertyChanged("Estatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstatusDescripcion {
            get {
                return this.EstatusDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.EstatusDescripcionField, value) != true)) {
                    this.EstatusDescripcionField = value;
                    this.RaisePropertyChanged("EstatusDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal IC {
            get {
                return this.ICField;
            }
            set {
                if ((this.ICField.Equals(value) != true)) {
                    this.ICField = value;
                    this.RaisePropertyChanged("IC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ICSI {
            get {
                return this.ICSIField;
            }
            set {
                if ((this.ICSIField.Equals(value) != true)) {
                    this.ICSIField = value;
                    this.RaisePropertyChanged("ICSI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal IE {
            get {
                return this.IEField;
            }
            set {
                if ((this.IEField.Equals(value) != true)) {
                    this.IEField = value;
                    this.RaisePropertyChanged("IE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal IR {
            get {
                return this.IRField;
            }
            set {
                if ((this.IRField.Equals(value) != true)) {
                    this.IRField = value;
                    this.RaisePropertyChanged("IR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ITC {
            get {
                return this.ITCField;
            }
            set {
                if ((this.ITCField.Equals(value) != true)) {
                    this.ITCField = value;
                    this.RaisePropertyChanged("ITC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RSI {
            get {
                return this.RSIField;
            }
            set {
                if ((this.RSIField.Equals(value) != true)) {
                    this.RSIField = value;
                    this.RaisePropertyChanged("RSI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RT {
            get {
                return this.RTField;
            }
            set {
                if ((this.RTField.Equals(value) != true)) {
                    this.RTField = value;
                    this.RaisePropertyChanged("RT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string plan {
            get {
                return this.planField;
            }
            set {
                if ((object.ReferenceEquals(this.planField, value) != true)) {
                    this.planField = value;
                    this.RaisePropertyChanged("plan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FiltroBusquedaEmpleadoDTO", Namespace="http://schemas.datacontract.org/2004/07/VESCServices.ENT.Entities")]
    [System.SerializableAttribute()]
    public partial class FiltroBusquedaEmpleadoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> EmpleadoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> EmpleadoPadreIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EmpresaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> EstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RazonSocialIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> EmpleadoID {
            get {
                return this.EmpleadoIDField;
            }
            set {
                if ((this.EmpleadoIDField.Equals(value) != true)) {
                    this.EmpleadoIDField = value;
                    this.RaisePropertyChanged("EmpleadoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> EmpleadoPadreID {
            get {
                return this.EmpleadoPadreIDField;
            }
            set {
                if ((this.EmpleadoPadreIDField.Equals(value) != true)) {
                    this.EmpleadoPadreIDField = value;
                    this.RaisePropertyChanged("EmpleadoPadreID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EmpresaId {
            get {
                return this.EmpresaIdField;
            }
            set {
                if ((this.EmpresaIdField.Equals(value) != true)) {
                    this.EmpresaIdField = value;
                    this.RaisePropertyChanged("EmpresaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Estatus {
            get {
                return this.EstatusField;
            }
            set {
                if ((this.EstatusField.Equals(value) != true)) {
                    this.EstatusField = value;
                    this.RaisePropertyChanged("Estatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RazonSocialId {
            get {
                return this.RazonSocialIdField;
            }
            set {
                if ((this.RazonSocialIdField.Equals(value) != true)) {
                    this.RazonSocialIdField = value;
                    this.RaisePropertyChanged("RazonSocialId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogoutResponseDTO", Namespace="http://schemas.datacontract.org/2004/07/VESCServices.ENT.Response.Account")]
    [System.SerializableAttribute()]
    public partial class LogoutResponseDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VESC.ServiceReference.ErrorDTO[] ErrorListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VESC.ServiceReference.ErrorDTO[] ErrorList {
            get {
                return this.ErrorListField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorListField, value) != true)) {
                    this.ErrorListField = value;
                    this.RaisePropertyChanged("ErrorList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRazonSocialResponseDTO", Namespace="http://schemas.datacontract.org/2004/07/VESCServices.ENT.Request.RazonSocial")]
    [System.SerializableAttribute()]
    public partial class GetRazonSocialResponseDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VESC.ServiceReference.RazonSocialDTO[] ListaRazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VESC.ServiceReference.RazonSocialDTO[] ListaRazonSocial {
            get {
                return this.ListaRazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaRazonSocialField, value) != true)) {
                    this.ListaRazonSocialField = value;
                    this.RaisePropertyChanged("ListaRazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RazonSocialDTO", Namespace="http://schemas.datacontract.org/2004/07/VESCServices.ENT.Entities")]
    [System.SerializableAttribute()]
    public partial class RazonSocialDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VESC.ServiceReference.EmpresaDTO EmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string calleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string coloniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empresa1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool estatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaInsertField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> fechaUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idRazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string municipioDelegacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numeroExtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numeroIntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string razonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rfcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stringVigenciaFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stringVigenciaInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioInsertField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime vigenciaFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime vigenciaInicioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VESC.ServiceReference.EmpresaDTO Empresa {
            get {
                return this.EmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresaField, value) != true)) {
                    this.EmpresaField = value;
                    this.RaisePropertyChanged("Empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string calle {
            get {
                return this.calleField;
            }
            set {
                if ((object.ReferenceEquals(this.calleField, value) != true)) {
                    this.calleField = value;
                    this.RaisePropertyChanged("calle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string colonia {
            get {
                return this.coloniaField;
            }
            set {
                if ((object.ReferenceEquals(this.coloniaField, value) != true)) {
                    this.coloniaField = value;
                    this.RaisePropertyChanged("colonia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cp {
            get {
                return this.cpField;
            }
            set {
                if ((object.ReferenceEquals(this.cpField, value) != true)) {
                    this.cpField = value;
                    this.RaisePropertyChanged("cp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string empresa1 {
            get {
                return this.empresa1Field;
            }
            set {
                if ((object.ReferenceEquals(this.empresa1Field, value) != true)) {
                    this.empresa1Field = value;
                    this.RaisePropertyChanged("empresa1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool estatus {
            get {
                return this.estatusField;
            }
            set {
                if ((this.estatusField.Equals(value) != true)) {
                    this.estatusField = value;
                    this.RaisePropertyChanged("estatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaInsert {
            get {
                return this.fechaInsertField;
            }
            set {
                if ((this.fechaInsertField.Equals(value) != true)) {
                    this.fechaInsertField = value;
                    this.RaisePropertyChanged("fechaInsert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechaUpdate {
            get {
                return this.fechaUpdateField;
            }
            set {
                if ((this.fechaUpdateField.Equals(value) != true)) {
                    this.fechaUpdateField = value;
                    this.RaisePropertyChanged("fechaUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEmpresa {
            get {
                return this.idEmpresaField;
            }
            set {
                if ((this.idEmpresaField.Equals(value) != true)) {
                    this.idEmpresaField = value;
                    this.RaisePropertyChanged("idEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idRazonSocial {
            get {
                return this.idRazonSocialField;
            }
            set {
                if ((this.idRazonSocialField.Equals(value) != true)) {
                    this.idRazonSocialField = value;
                    this.RaisePropertyChanged("idRazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string municipioDelegacion {
            get {
                return this.municipioDelegacionField;
            }
            set {
                if ((object.ReferenceEquals(this.municipioDelegacionField, value) != true)) {
                    this.municipioDelegacionField = value;
                    this.RaisePropertyChanged("municipioDelegacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numeroExt {
            get {
                return this.numeroExtField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroExtField, value) != true)) {
                    this.numeroExtField = value;
                    this.RaisePropertyChanged("numeroExt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numeroInt {
            get {
                return this.numeroIntField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroIntField, value) != true)) {
                    this.numeroIntField = value;
                    this.RaisePropertyChanged("numeroInt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string razonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.razonSocialField, value) != true)) {
                    this.razonSocialField = value;
                    this.RaisePropertyChanged("razonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rfc {
            get {
                return this.rfcField;
            }
            set {
                if ((object.ReferenceEquals(this.rfcField, value) != true)) {
                    this.rfcField = value;
                    this.RaisePropertyChanged("rfc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stringVigenciaFinal {
            get {
                return this.stringVigenciaFinalField;
            }
            set {
                if ((object.ReferenceEquals(this.stringVigenciaFinalField, value) != true)) {
                    this.stringVigenciaFinalField = value;
                    this.RaisePropertyChanged("stringVigenciaFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stringVigenciaInicio {
            get {
                return this.stringVigenciaInicioField;
            }
            set {
                if ((object.ReferenceEquals(this.stringVigenciaInicioField, value) != true)) {
                    this.stringVigenciaInicioField = value;
                    this.RaisePropertyChanged("stringVigenciaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuarioInsert {
            get {
                return this.usuarioInsertField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioInsertField, value) != true)) {
                    this.usuarioInsertField = value;
                    this.RaisePropertyChanged("usuarioInsert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuarioUpdate {
            get {
                return this.usuarioUpdateField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioUpdateField, value) != true)) {
                    this.usuarioUpdateField = value;
                    this.RaisePropertyChanged("usuarioUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime vigenciaFinal {
            get {
                return this.vigenciaFinalField;
            }
            set {
                if ((this.vigenciaFinalField.Equals(value) != true)) {
                    this.vigenciaFinalField = value;
                    this.RaisePropertyChanged("vigenciaFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime vigenciaInicio {
            get {
                return this.vigenciaInicioField;
            }
            set {
                if ((this.vigenciaInicioField.Equals(value) != true)) {
                    this.vigenciaInicioField = value;
                    this.RaisePropertyChanged("vigenciaInicio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpresaDTO", Namespace="http://schemas.datacontract.org/2004/07/VESCServices.ENT.Entities")]
    [System.SerializableAttribute()]
    public partial class EmpresaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoMContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoPContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string empresa1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool estatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaInsertField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> fechaUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string puestoContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefono2ContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioInsertField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioUpdateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidoMContacto {
            get {
                return this.apellidoMContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoMContactoField, value) != true)) {
                    this.apellidoMContactoField = value;
                    this.RaisePropertyChanged("apellidoMContacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidoPContacto {
            get {
                return this.apellidoPContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoPContactoField, value) != true)) {
                    this.apellidoPContactoField = value;
                    this.RaisePropertyChanged("apellidoPContacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correoContacto {
            get {
                return this.correoContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoContactoField, value) != true)) {
                    this.correoContactoField = value;
                    this.RaisePropertyChanged("correoContacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string empresa1 {
            get {
                return this.empresa1Field;
            }
            set {
                if ((object.ReferenceEquals(this.empresa1Field, value) != true)) {
                    this.empresa1Field = value;
                    this.RaisePropertyChanged("empresa1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool estatus {
            get {
                return this.estatusField;
            }
            set {
                if ((this.estatusField.Equals(value) != true)) {
                    this.estatusField = value;
                    this.RaisePropertyChanged("estatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaInsert {
            get {
                return this.fechaInsertField;
            }
            set {
                if ((this.fechaInsertField.Equals(value) != true)) {
                    this.fechaInsertField = value;
                    this.RaisePropertyChanged("fechaInsert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechaUpdate {
            get {
                return this.fechaUpdateField;
            }
            set {
                if ((this.fechaUpdateField.Equals(value) != true)) {
                    this.fechaUpdateField = value;
                    this.RaisePropertyChanged("fechaUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEmpresa {
            get {
                return this.idEmpresaField;
            }
            set {
                if ((this.idEmpresaField.Equals(value) != true)) {
                    this.idEmpresaField = value;
                    this.RaisePropertyChanged("idEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idLogin {
            get {
                return this.idLoginField;
            }
            set {
                if ((this.idLoginField.Equals(value) != true)) {
                    this.idLoginField = value;
                    this.RaisePropertyChanged("idLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreContacto {
            get {
                return this.nombreContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreContactoField, value) != true)) {
                    this.nombreContactoField = value;
                    this.RaisePropertyChanged("nombreContacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string puestoContacto {
            get {
                return this.puestoContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.puestoContactoField, value) != true)) {
                    this.puestoContactoField = value;
                    this.RaisePropertyChanged("puestoContacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono2Contacto {
            get {
                return this.telefono2ContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefono2ContactoField, value) != true)) {
                    this.telefono2ContactoField = value;
                    this.RaisePropertyChanged("telefono2Contacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefonoContacto {
            get {
                return this.telefonoContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoContactoField, value) != true)) {
                    this.telefonoContactoField = value;
                    this.RaisePropertyChanged("telefonoContacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuarioInsert {
            get {
                return this.usuarioInsertField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioInsertField, value) != true)) {
                    this.usuarioInsertField = value;
                    this.RaisePropertyChanged("usuarioInsert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuarioUpdate {
            get {
                return this.usuarioUpdateField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioUpdateField, value) != true)) {
                    this.usuarioUpdateField = value;
                    this.RaisePropertyChanged("usuarioUpdate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IVescService")]
    public interface IVescService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVescService/Login", ReplyAction="http://tempuri.org/IVescService/LoginResponse")]
        VESC.ServiceReference.LoginResponseDTO Login(VESC.ServiceReference.LoginRequestDTO request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVescService/Logout", ReplyAction="http://tempuri.org/IVescService/LogoutResponse")]
        VESC.ServiceReference.LogoutResponseDTO Logout(VESC.ServiceReference.LogoutRequestDTO request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVescService/SendPassword", ReplyAction="http://tempuri.org/IVescService/SendPasswordResponse")]
        VESC.ServiceReference.SendPasswordResponseDTO SendPassword(VESC.ServiceReference.SendPasswordRequestDTO request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVescService/ChangePassword", ReplyAction="http://tempuri.org/IVescService/ChangePasswordResponse")]
        VESC.ServiceReference.ChangePasswordResponseDTO ChangePassword(VESC.ServiceReference.ChangePasswordRequestDTO request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVescService/AltaEmpleado", ReplyAction="http://tempuri.org/IVescService/AltaEmpleadoResponse")]
        VESC.ServiceReference.AltaEmpleadoResponseDTO AltaEmpleado(VESC.ServiceReference.AltaEmpleadoRequestDTO request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVescService/EditEmpleado", ReplyAction="http://tempuri.org/IVescService/EditEmpleadoResponse")]
        VESC.ServiceReference.EditEmpleadoResponseDTO EditEmpleado(VESC.ServiceReference.EditEmpleadoRequestDTO request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVescService/AltaDependiente", ReplyAction="http://tempuri.org/IVescService/AltaDependienteResponse")]
        VESC.ServiceReference.AltaEmpleadoResponseDTO AltaDependiente(VESC.ServiceReference.AltaEmpleadoRequestDTO request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVescService/BuscarEmpleado", ReplyAction="http://tempuri.org/IVescService/BuscarEmpleadoResponse")]
        VESC.ServiceReference.BuscarEmpleadoResponseDTO BuscarEmpleado(VESC.ServiceReference.BuscarEmpleadoRequestDTO request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVescService/ConsultaPadron", ReplyAction="http://tempuri.org/IVescService/ConsultaPadronResponse")]
        VESC.ServiceReference.ConsultaPadronResponseDTO ConsultaPadron(VESC.ServiceReference.ConsultaPadronRequestDTO request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVescService/GetRazonSocial", ReplyAction="http://tempuri.org/IVescService/GetRazonSocialResponse")]
        VESC.ServiceReference.GetRazonSocialResponseDTO GetRazonSocial(VESC.ServiceReference.GetRazonSocialRequestDTO request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVescServiceChannel : VESC.ServiceReference.IVescService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VescServiceClient : System.ServiceModel.ClientBase<VESC.ServiceReference.IVescService>, VESC.ServiceReference.IVescService {
        
        public VescServiceClient() {
        }
        
        public VescServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VescServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VescServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VescServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VESC.ServiceReference.LoginResponseDTO Login(VESC.ServiceReference.LoginRequestDTO request) {
            return base.Channel.Login(request);
        }
        
        public VESC.ServiceReference.LogoutResponseDTO Logout(VESC.ServiceReference.LogoutRequestDTO request) {
            return base.Channel.Logout(request);
        }
        
        public VESC.ServiceReference.SendPasswordResponseDTO SendPassword(VESC.ServiceReference.SendPasswordRequestDTO request) {
            return base.Channel.SendPassword(request);
        }
        
        public VESC.ServiceReference.ChangePasswordResponseDTO ChangePassword(VESC.ServiceReference.ChangePasswordRequestDTO request) {
            return base.Channel.ChangePassword(request);
        }
        
        public VESC.ServiceReference.AltaEmpleadoResponseDTO AltaEmpleado(VESC.ServiceReference.AltaEmpleadoRequestDTO request) {
            return base.Channel.AltaEmpleado(request);
        }
        
        public VESC.ServiceReference.EditEmpleadoResponseDTO EditEmpleado(VESC.ServiceReference.EditEmpleadoRequestDTO request) {
            return base.Channel.EditEmpleado(request);
        }
        
        public VESC.ServiceReference.AltaEmpleadoResponseDTO AltaDependiente(VESC.ServiceReference.AltaEmpleadoRequestDTO request) {
            return base.Channel.AltaDependiente(request);
        }
        
        public VESC.ServiceReference.BuscarEmpleadoResponseDTO BuscarEmpleado(VESC.ServiceReference.BuscarEmpleadoRequestDTO request) {
            return base.Channel.BuscarEmpleado(request);
        }
        
        public VESC.ServiceReference.ConsultaPadronResponseDTO ConsultaPadron(VESC.ServiceReference.ConsultaPadronRequestDTO request) {
            return base.Channel.ConsultaPadron(request);
        }
        
        public VESC.ServiceReference.GetRazonSocialResponseDTO GetRazonSocial(VESC.ServiceReference.GetRazonSocialRequestDTO request) {
            return base.Channel.GetRazonSocial(request);
        }
    }
}
